[package]
name = "rbxfs"
version = "0.1.0"
authors = ["Lucien Greathouse <me@lpghatguy.com>"]
description = "Transfers Roblox objects to and from the filesystem"

[dependencies]
clap = "2.27.1"
rouille = "1.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
notify = "4.0.0"
